"""Optional, offline graph presentation; importing compute does not load a viewer."""

from .adapter import build_graph
from .export import export_html, export_html_report, render_html
from .model_adapter import build_model_graph
from .visual_chevrons import build_execution_chevrons, build_variant_visualization
from .visual_contracts import (
    ChartPanel,
    ChartPoint,
    ChartSeries,
    ChevronEvent,
    ChevronLane,
    ChevronPanel,
    GraphPanel,
    MatrixCell,
    MatrixPanel,
    TablePanel,
    TimelineItem,
    TimelineLane,
    TimelinePanel,
    VisualEdge,
    VisualField,
    VisualizationDocument,
    VisualMetric,
    VisualNode,
    VisualProvenance,
)
from .visualization import (
    UnsupportedVisualizationError,
    build_model_visualization,
    build_variant_duration,
    build_visualization,
    compare_footprints,
    read_visualization,
    visualization_json_bytes,
    write_visualization,
)

__all__ = (
    "build_graph",
    "build_model_graph",
    "build_visualization",
    "build_model_visualization",
    "build_variant_duration",
    "build_variant_visualization",
    "build_execution_chevrons",
    "compare_footprints",
    "export_html",
    "export_html_report",
    "render_html",
    "read_visualization",
    "write_visualization",
    "visualization_json_bytes",
    "UnsupportedVisualizationError",
    "VisualizationDocument",
    "VisualProvenance",
    "VisualField",
    "VisualMetric",
    "VisualNode",
    "VisualEdge",
    "GraphPanel",
    "MatrixCell",
    "MatrixPanel",
    "ChartPoint",
    "ChartSeries",
    "ChartPanel",
    "ChevronLane",
    "ChevronEvent",
    "ChevronPanel",
    "TimelineLane",
    "TimelineItem",
    "TimelinePanel",
    "TablePanel",
)
